# -*- coding: utf-8 -*-
"""sentenceclass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pma9y0tLZO-nObSuhtDCVcOpeQW-m2RZ
"""

import pandas as pd
from collections import Counter

def classify(sentence):
    keywords_syllabus = ["syllabus", "schedule", "office hours", "grade structure", "ta","grade"
    ,"date","assignments","assignment","section","class","term","day","days","time","times","proffesor","email","hours","office","earning Objectives","learning","final","mideterm","grading"]
    keywords_math = ["O(n)", "algorithm time complexity", "mathematics","plus","add","subtract","derivative","integral","complexity","time","times","run time","runtime","multiply"]
    keywords_general = ["merge sort", "binary search tree", "algorithm analysis","explain","how","does","algorithm","code","what","concept","example","analize","data","structure"]

    sentence = sentence.lower()

    # Count how many times words in the sentence appear in each group
    count_syllabus = sum(keyword in sentence for keyword in keywords_syllabus)
    count_math = sum(keyword in sentence for keyword in keywords_math)
    count_general = sum(keyword in sentence for keyword in keywords_general)

    # Find the most popular group
    counts = {
        "Syllabus-related": count_syllabus,
        "Math-related": count_math,
        "General": count_general,

    }

    most_popular_group = max(counts, key=counts.get)
    return most_popular_group if counts[most_popular_group] > 0 else "General"

input_data = pd.read_csv("VirtualTADataSet.csv", header=None)
categories = []

for sentence in input_data[1]:
    category = classify(sentence)
    categories.append(category)

input_data["Category"] = categories

input_data.to_csv("classified_data.csv", index=False, header=["Number", "Sentence", "Category"])
print(input_data)
